name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr list -l autoupdate | cut -f1 | while read line ; gh pr comment $like --body "autoupdate"; done
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f3 | while read line ; git checkout $line && git merge origin/main && git push; done
        env:
          GH_TOKEN: ${{ github.token }}