name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: andruhon/try-autoupdate-simple
      - run: |
          git fetch --unshallow
          git config user.name github-actions
          git config user.email github-actions@github.com
          gh pr list -l autoupdate | cut -f3 | while read line
          do
            git checkout -b $line origin/$line
            git merge origin/main -m"Merge branch 'main' into $line (automerge)"
            git push
          done
