name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git status && git fetch --unshallow
        env:
          GH_TOKEN: ${{ github.token }}
      - run: git status && git log --oneline -n 5
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f1 | while read line ; do gh pr comment $line --body "autoupdate" ; done
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f3 | while read line ; git checkout -b $line origin/$line && git merge origin/main -m"autoupdate to main" && git push ; done
        env:
          GH_TOKEN: ${{ github.token }}