name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --unshallow
          git config user.name github-actions
          git config user.email github-actions@github.com
          gh pr list -l autoupdate | cut -f3 | while read line
          do
            git checkout -b $line origin/$line
            git merge origin/main -m"Merge branch 'main' into $line (automerge)"
            git push
            git rev-parse HEAD | {
              read cmt
              gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/andruhon/try-autoupdate-simple/check-suites \
                -f "head_sha=$cmt"
            }
          done
        env:
          GH_TOKEN: ${{ github.token }}
