name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr list -l autoupdate | cut -f1 | while read line ; do gh pr comment $line --body "autoupdate" ; done
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f3 | while read line ; do git checkout -b $line origin/$line && git merge origin/main && git push ; done
        env:
          GH_TOKEN: ${{ github.token }}