name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh pr list -l autoupdate | cut -f1 | while read line
          do
            gh pr update-branch branch $line
          done
        env:
          GH_TOKEN: ${{ github.token }}
