name: build

on:
  push:
  workflow_dispatch:
  check_run:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4 
      - run: pwd
      - run: ls
      - run: git status
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr status
        env:
          GH_TOKEN: ${{ github.token }}
          
  complete:
    name: complete
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          git rev-parse --abbrev-ref HEAD | {
            read brc
            gh br checks $brc
          }
        env:
          GH_TOKEN: ${{ github.token }}