name: build

on:
  push:
  workflow_dispatch:
  check_run:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4 
      - run: pwd
      - run: ls
      - run: git status
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr status
        env:
          GH_TOKEN: ${{ github.token }}
          
  complete:
    name: complete
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          git rev-parse --abbrev-ref HEAD | {
            read brc
            runurl=$(gh pr checks test5 --json name,link -q 'map(select(.name=="build").link)[0]')
            runid=${runurl##*/}
            echo $runid
            gh api \
                --method PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/andruhon/try-autoupdate-simple/check-runs/$runid \
                -f "name=build" -f "status=completed" -f "conclusion=success" -f "details_url=https://github.com/andruhon/try-autoupdate-simple/actions" \
                -f "output[title]=Build" -f "output[summary]=this build was triggered by autoupdate" \
                -f "output[text]=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 
          }
        env:
          GH_TOKEN: ${{ github.token }}